### ISSUE TITLE
Static build using depends fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by shaavan** [bitcoin-core/gui-qml#129]
I tried to compile QML using the following sets of steps:

```
cd depends
make -j8
cd ..
./autogen.sh
CONFIG_SITE=\$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure --without-bdb --with-qml
make -j8
```

But the process fails at the depends on building stage, with the following error:

![image](https://user-images.githubusercontent.com/85434418/171995064-681226dd-5873-4a8d-a9e3-f5e145c10d34.png)

I went to the link (https://bitcoincore.org/depends-sources), which shows a 404 error initially.
It turns out there is no page of that sort available.

![image](https://user-images.githubusercontent.com/85434418/171995116-00fcb71f-d9c7-4896-883e-5423d5bc3908.png)

**There can be two scenarios at play:**

- The depends have faulty links. In which case it needs to be fixed
- I am making some errors in the steps I took to do the static build. In which case, I would humbly ask other contributors to direct me.

**Comment by hebasto** [comment]
https://bitcoincore.org/depends-sources is a backup source for dependencies. But we cannot rely on it in this repo.

Links  `https://download.qt.io/official_releases/qt/5.15/5.15.3/submodules/...` should work.

**Comment by hebasto** [comment]
Just checked: https://bitcoincore.org/depends-sources/qtbase-everywhere-opensource-src-5.15.3.tar.xz works for as well.

**Comment by hebasto** [comment]
Closing, as the main repository backup downloads won't be updated with QML-specific files.

**Comment by hebasto** [comment]
@shaavan 
> I would humbly ask other contributors to direct me.

Just try one more time, maybe after `make -C depends clean-all`.

If OpenSSL error appears again, check you internet connection (settings, stack etc).

**Comment by shaavan** [comment]
**Issue solved:**

Using a VPN prevented the OpenSSL error.
