### ISSUE TITLE
Misaligned ExternalLink and OptionsButton

### ISSUE THREAD

**Issue by shaavan** [bitcoin-core/gui-qml#159]
The **ExternalLink** and **OptionsButton** displayed by `Settings.qml` are not properly right-aligned. 

Here are some screenshots addressing this issue:

![Screenshot from 2022-08-15 19-24-34](https://user-images.githubusercontent.com/85434418/184650306-d0869698-47ee-490f-98aa-87fefd758f5a.png)
![Screenshot from 2022-08-15 19-23-26](https://user-images.githubusercontent.com/85434418/184650318-9e99a4ce-efea-4f6c-b5b0-6700139c44ea.png)
![Screenshot from 2022-08-15 19-35-09](https://user-images.githubusercontent.com/85434418/184650502-001cd39f-67ae-4a05-adf5-9b13ed58bb8d.png)

I experimented with different Layouts and anchor settings, which I suspected to be the cause of misalignment; however, it does not seem to fix this issue.
Interestingly the **ValueInput** items are properly right-aligned, even though it does not seem to have alignment settings different from the abovementioned components.

There is a finite possibility that this can be a bug with the qml itself. Hence I urge other contributors as well to look through this issue.

**Comment by jarolrod** [comment]
The export and right caret icons, which represent the occurrences of `ExternalLink` are not supposed to be right aligned according to the design so that is correct.

The OptionsButton can probably set the inset on the control to 0.

**Comment by jarolrod** [comment]
This was fixed by #169
