### ISSUE TITLE
Brainstorm: On the loading of pages within a view container and focus policies

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui-qml#219]
When the OnboardingWizard is loaded, all pages within are all loaded. This has implications for tab functionality and accessibility features like screen readers.

If all pages are loaded, then by default; tabbing can go onto other pages that are not in view essentially making tabbing useless, and screenreader can go off the page, also making them useless.

It appears we have two options to address this:

## Option A: Only load one page at a time

We can edit/choose containers that will only have one page loaded at a time. The action of continuing to the next page or going back to a previous page will be responsible for containing the logic that will allow for the correct animation to show.

The SwipeView [documentation](https://doc.qt.io/qt-6/qml-qtquick-controls2-swipeview.html) contains info on how to limit the amount of pages loaded, and 

![OPTION-A](https://user-images.githubusercontent.com/23396902/212800119-92cfe469-fa8e-4804-8766-3cbad887c83a.png)

## Option B: Make a hard boundary between pages

We can make hard boundaries between pages by playing around with focus policies (maybe): https://doc.qt.io/qt-6/qtquick-input-focus.html

I'm not so clear on how we would accomplish this one, but conceptually it's possible.

![OPTION-B](https://user-images.githubusercontent.com/23396902/212800195-d3cb0a9f-7785-46df-98fd-e4f04840df67.png)

**Comment by johnny9** [comment]
An option is to control the flow of focus with KeyNavigation attached properties. https://github.com/johnny9/gui-qml/commits/tab-focus-navigation. The downside to this is it can be very fragile and will require tests to prevent regression.

**Comment by johnny9** [comment]
While playing with the KeyNavigation my initial thought for fixing this was some form of Option A where the SwipeViews are reimplemented with StackViews using animations. However, I haven't validated what the tab focus chain is like for StackView.
