### ISSUE TITLE
The Settings hitbox should be the entire setting itself

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui-qml#228]
![2023-01-26_21-09](https://user-images.githubusercontent.com/23396902/214995388-c5655583-8ef9-4446-9b3b-cee369f67bcb.png)

In the above screenshot, and on master, the hitbox for a setting is the action item itself; nothing else is clickable.

Instead, the hitbox should be the entire area of the setting. This new hitbox which covers the entire setting row area should engage the action item. This means that when looking at the above screenshot:
- In the first setting, the external link will be engaged
- In the second setting, the value input field will be engaged
- In the last setting, the switch will be toggled

**Comment by johnny9** [comment]
https://github.com/bitcoin-core/gui-qml/pull/240
