### ISSUE TITLE
Introduce Continue Button states in adherance to the design file specifications

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui-qml#229]
![2023-01-26_21-18](https://user-images.githubusercontent.com/23396902/214996299-66a380cc-4b0e-4339-ab38-7b2c10cb0f15.png)

We are missing some states for the continue button which are defined in the design file:

| default (implemented) | [Hover](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=4998%3A115821&t=jEuoyzc9hL6siGb8-4) | [Pressed](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=4998%3A115884&t=jEuoyzc9hL6siGb8-4) | [Focused](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=4998%3A116010&t=jEuoyzc9hL6siGb8-4) |
| --------------------- | ----- | ------- | ------- |
| ![Content=Label, Style=Filled, Size=Large, State=Default](https://user-images.githubusercontent.com/23396902/214997884-42e93946-21f4-4159-9c83-2672e5f3f9b8.png) | ![Content=Label, Style=Filled, Size=Large, State=Hover](https://user-images.githubusercontent.com/23396902/214997905-81eb5f7d-a88d-4bd6-9fb0-e826e7327269.png) | ![Content=Label, Style=Filled, Size=Large, State=Pressed](https://user-images.githubusercontent.com/23396902/214997943-99755201-f6d7-48e6-b740-b1224f88aabe.png) | ![Content=Label, Style=Filled, Size=Large, State=Focused](https://user-images.githubusercontent.com/23396902/214998068-1a1a1b24-2d99-478e-9aa5-e955c1b08400.png) |

https://github.com/bitcoin-core/gui-qml/pull/214 would handle the Focused state.

**Comment by jarolrod** [comment]
@gbks are there any specifications for animation between states?

**Comment by GBKS** [comment]
For buttons, I usually put a 150ms transition duration. For text-based ones 100ms. Maybe start with those and see how it feels? Should be snappy enough so it feels really responsive, but still smooth (meaning not abrupt).
