### ISSUE TITLE
Introduce Current Network Indicator 

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui-qml#233]
Introduce the Current Network Indicator component which signals to the user what network they are currently on, per the [design file](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=6010%3A67978&t=r2HCxG2ibuXXCYWM-4)

![Block clock-2](https://user-images.githubusercontent.com/23396902/215309114-69045227-fb5b-4edb-91ed-80e22dfd53cf.png)

**Comment by anmode** [comment]
<img width="783" alt="Screenshot 2023-01-30 at 10 19 19 AM" src="https://user-images.githubusercontent.com/88332977/215390037-a2464105-960f-4f00-b0e4-65f68dd8bf5a.png">


How is it? I tried to introduce the current network indicator.

**Comment by jarolrod** [comment]
@anmode the current network indicator *is* the colored box you see below the block clock, that's whats needed to be implemented. No more states of this component are needed. 

There's an indicator for every network except main as that is not needed.

**Comment by anmode** [comment]
> @anmode the current network indicator *is* the colored box you see below the block clock, that's whats needed to be implemented. No more states of this component are needed. 
> 
> There's an indicator for every network except main as that is not needed.

Ohh my bad! I got it now.
I code then nd generate pR for the same!
