### ISSUE TITLE
V1: Meta Issue

### ISSUE THREAD

**Issue by jarolrod** [bitcoin-core/gui-qml#248]
V1 release is approaching, this is a meta issue detailing the remaining tasks to complete before we can release:

#### TODO ✍️
1. - [ ] Add ability to choose a custom datadirectory
     - This would introduce a [FileDialog](https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html) because it's fallback is in qml, instead of a Qt Widgets fallback. A Qt widgets fallback is a non-starter
     - The FileDialog will set [selectFolder](https://doc.qt.io/qt-5/qml-qtquick-dialogs-filedialog.html#selectFolder-prop) to `true`
     - This requires enabling the missing modules in depends which can be found in the following list: [DefaultFileDialog.qml includes](https://github.com/qt/qtquickcontrols/blob/47aa3c15b4badb3b7284c3eb32d2a2314ec8f7f2/src/dialogs/DefaultFileDialog.qml#L40-L50)
2. - [ ] Update `OptionsModel` to keep track of what settings are being updated, and only write to `settings.json` when told to do so
     - During Onboarding, this would be when the user has completed onboarding
     - After Onboarding, this can be whenever a setting is updated and in real time
3. - [ ] Warn that setting changed while node is running will not come into effect until node restart
     - needs design consideration: https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/43
4. - [ ] Have UI signal when a setting is being overridden by command-line or bitcoin.conf 
     - needs design consideration: https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/44
5. - [ ] Find a solution to the [loading and focus policy](https://github.com/bitcoin-core/gui-qml/issues/219) so that tab focus navigation can work properly
6. - [ ] Testing guide to be published on [bitcoincore.app](https://bitcoincore.app/)

### Completed ✅
1. - [x] Better representation of [remaining sync time](https://github.com/bitcoin-core/gui-qml/issues/225) in block clock
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/249
2. - [x] Introduce the PeersIndicator component into the BlockClock
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/236)
3. - [x] Wire up Developer Options to OptionsModel
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/224)
4. - [x] Introduce the [Current Network Indicator component](https://github.com/bitcoin-core/gui-qml/issues/233)
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/251
5. - [x] Update ExternalLink icon to fit with design file
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/239)
6. - [x] Disable the Prune target setting when the `Prune` toggle switch is disabled 
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/243
7. - [x] BlockClock [needs](https://github.com/bitcoin-core/gui-qml/issues/226) a connecting state with an [animation](https://bitcoincore.app/assets/images/block-clock/states-big.png)
     - picked up by: https://github.com/bitcoin-core/gui-qml/pull/252 (missing animation)
8. - [x] [Peer Window](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=5964%3A16801&t=974BMHjLSBEQNBh4-4)
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/259
9. - [x] Introduce definition of the focus outline for focus-able component
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/264
10. - [x] Do not show the onboarding wizard if `settings.json` or `bitcoin.conf` exist in default datadir or in supplied `-datadir`
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/247
11. - [x] Add an OptionButton to StorageOptions that represents a custom prune target set by a user after they have configured a prune target in `Detailed Settings` during onboarding 
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/245

12. - [x] Introduce and setup Proxy configuration
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/223)
13. - [x] Implement a new control in place of `ValueInput` that:
      - only accepts numbers as input, and does some simple validation on the input number to make sure it's valid (Probably should be a [TextInput](https://doc.qt.io/qt-5/qml-qtquick-controls-textfield.html), setting a proper [inputMethodHint](https://doc.qt.io/qt-5/qml-qtquick-controls-textinput.html#inputMethodHints-prop) with an [IntValidator](https://doc.qt.io/qt-5/qml-qtquick-controls-textfield.html#validator-prop)) 
      - When a value is invalid the following warning should be represented within the setting
      - picked up by: https://github.com/bitcoin-core/gui-qml/pull/257

### Stretch-Goals

1. - [ ] Initial testing setup (started in: https://github.com/bitcoin-core/gui-qml/pull/215)
2. - [ ] Console Window
3. - [ ] Translations

**Comment by hebasto** [comment]
Closing this. Let's continue work in issues and PRs tagged with dedicated [milestones](https://github.com/bitcoin-core/gui-qml/milestones). No need in umbrella issue for a milestone.
