### ISSUE TITLE
Remove unnecessary line breaks

### ISSUE THREAD

**Issue by GBKS** [bitcoin-core/gui-qml#282]
The copy in the Figma designs included some custom line breaks to make the shape of the text look nicer (common thing these goofy designers do). These were ported into the code. Since the application width is flexible, this can cause line breaks in awkward places. Let's remove them.

- Strengthen bitcoin screen, line break between "bitcoin" and "so" ([code](https://github.com/bitcoin-core/gui-qml/blob/18dfb2cac7e81b00d42bc84d35c0d1b8e6963982/src/qml/pages/onboarding/OnboardingStrengthen.qml#L23))
- Block clock screen, line break between "every" and "10", and "dial" and "that" ([code](https://github.com/bitcoin-core/gui-qml/blob/18dfb2cac7e81b00d42bc84d35c0d1b8e6963982/src/qml/pages/onboarding/OnboardingBlockclock.qml#L23))

#### Useful skills:

Just some basic text edits.

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by jarolrod** [comment]
This was fixed by https://github.com/bitcoin-core/gui-qml/pull/283
