### ISSUE TITLE
Set minimum block clock size to 200px width

### ISSUE THREAD

**Issue by GBKS** [bitcoin-core/gui-qml#382]
### Issues, reports or feature requests related to the GUI should be opened directly on the GUI repo

- [X] I still think this issue should be opened here

### Report

On my Android phone, the clock is too small. Minimum size should be 200px width. It is ~131px wide.

![image](https://github.com/bitcoin-core/gui-qml/assets/695901/6aa973ec-91f2-4f38-abba-3f274cfa56d8)

**Comment by D33r-Gee** [comment]
Hi @GBKS , what android device are you using?

**Comment by GBKS** [comment]
It's a Galaxy A32 5G.

**Comment by D33r-Gee** [comment]
> It's a Galaxy A32 5G.

Great I will test with a virtual device...

Also to make sure I'm able to reproduce it, which build are you using? Latest on main branch?

**Comment by GBKS** [comment]
The math that defines the width is located [here](https://github.com/bitcoin-core/gui-qml/blob/67150efc17a17820193fbd5715e7fc92d417556a/src/qml/components/BlockClock.qml#L45).

`Math.min((root.parentWidth * dial.scale), (root.parentHeight * dial.scale))`

The Galaxy A32 has a logical resolution of 360x800. The dial scale is either 1/2 or 1/3. `parentWidth` is set [here](https://github.com/bitcoin-core/gui-qml/blob/67150efc17a17820193fbd5715e7fc92d417556a/src/qml/pages/node/NodeRunner.qml#L28) as the `parent.width - 40`. So that puts the width at `(360-40)/2 = 160` or `(360-40)/3 = ~107`. Not exactly the ~131 I roughly measured in my screenshot above, but both values are below the 200 minimum that we want. So maybe we change the line above to this?

`Math.max(200, Math.min((root.parentWidth * dial.scale), (root.parentHeight * dial.scale)))`

But that misses the scenario where the clock is shown in a widget. So you really don't want to go smaller than the screen width minus some padding. So maybe this?

`Math.max(Math.min(200, root.parentWidth - 30), Math.min((root.parentWidth * dial.scale), (root.parentHeight * dial.scale)))`

I am probably missing something, since my math above doesn't totally add up with my screenshot measurement.

Thanks for looking into this. I believe I am on the latest main branch.

**Comment by D33r-Gee** [comment]
@GBKS, thanks for your comment above, made my life very easy :)

build and tested with the change you suggested:

> `Math.max(Math.min(200, root.parentWidth - 30), Math.min((root.parentWidth * dial.scale), (root.parentHeight * dial.scale)))`

Results below:

Before change (this a screenshot of a Galaxy A32 5G virtual device):

![Screenshot_1703024712](https://github.com/bitcoin-core/gui-qml/assets/111142327/dee1ab06-7fc2-4885-b8ef-223bdeb7856a)

this a after the change:
![Screenshot_1703024560](https://github.com/bitcoin-core/gui-qml/assets/111142327/1326d460-53a5-43a3-b655-12d5d468b53d)

I'll go ahead a start a PR, unless there's more to consider?

**Comment by D33r-Gee** [comment]
@GBKS just opened the PR with your fix https://github.com/bitcoin-core/gui-qml/pull/385
