### ISSUE TITLE
Implement updated Create single-sig wallet flow

### ISSUE THREAD

**Issue by stackingsaunter** [bitcoin-core/gui-qml#404]
Here's handoff of Create single-sig wallet flow after round of user testing:

https://www.figma.com/design/CmK2n6zcXUqSTFV8QflP1d/Create-Wallet-Handoff?node-id=0-1&t=nmDB9OCUiurkQ4Jc-0

This assumes that users can’t/shouldn’t use wallet while IBD is in progress (and it’s not assumeUTXO) - If that's wrong the last part still might be updated in the future

**Comment by GBKS** [comment]
Awesome. Left a few comments.

Let me know if you disagree, I don't think that dropping a Figma file is sufficient for a hand-off. This one also includes a lot of screens that are not related to creation of a single-sig wallet. Only 6 of the screens are new, and there are minor changes to some of the others. We should split this out as much as we can and update the design docs accordingly. That should also help then with implementation.

The IBD part at the end is not related to the single-sig wallet flow and part of the activity screen milestone and design, so I think we don't need to discuss that here.

**Comment by stackingsaunter** [comment]
Closing the issue as it can be followed in design repo:

https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/62#issuecomment-2144760101
