### ISSUE TITLE
Create onboarding flow 

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-core/gui-qml#6]
Closed the Widgets GUI issue on onboarding considerations to re-open here.

Past discussion can be found here: https://github.com/bitcoin-core/gui/issues/81

**Comment by hebasto** [comment]
@Bosch-0 

Does https://github.com/bitcoin-core/gui/issues/81#issuecomment-697145700  point to the latest figma design files?

**Comment by Bosch-0** [comment]
The mockup I did in that original post can be found [here](https://www.figma.com/file/0oqnohjahRtprjRyaetDOL/Bitcoin-Core?node-id=2323%3A298).

Though I will be creating an onboarding flow from scratch for the QML GUI as that design was done within the constraints of widgets. 

We should focus any onboarding related discussions to this thread.

**Comment by hebasto** [comment]
See #43.

**Comment by GBKS** [comment]
Do we still need this issue? #43 was closed a month ago and while there is an onboarding flow in development in #127, the conversations around it are not happening in this thread.
